Repository AY2021S1-CS2113T-W12-4/tp, pull requests merged in 2020-10, with the labels that each got.

#57 Refactor storage related classes into storage package
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/duke/event/EventManager.java
  src/main/java/seedu/duke/storage/EventListDecoder.java
  src/main/java/seedu/duke/storage/EventListEncoder.java
  src/main/java/seedu/duke/storage/StorageManager.java
  src/test/java/seedu/duke/StorageTest.java
Labels: type.Task

#58 Add InvalidCommandException for the case when user enters an invalid …
  src/main/java/seedu/duke/exception/InvalidCommandException.java
  src/main/java/seedu/duke/parser/CommandParser.java
Labels: severity.High, type.Bug

#65 Branch storage assertions
  src/main/java/seedu/duke/storage/EventListDecoder.java
  src/main/java/seedu/duke/storage/EventListEncoder.java
  src/main/java/seedu/duke/storage/StorageManager.java
Labels: priority.Low, type.Task

#67 Add logging to StorageManager class
  src/main/java/seedu/duke/storage/StorageManager.java
Labels: priority.Low, type.Task

#68 Rename method in EventListEncoder
  src/main/java/seedu/duke/storage/EventListEncoder.java
Labels: priority.Low, type.Task

#70 Branch class exception
  src/main/java/seedu/duke/ClassManager.java
Labels: priority.Medium, type.Task

#71 Handle Assertions&logging for add&delete test
  data/events.txt
  src/main/java/seedu/duke/Test.java
  src/main/java/seedu/duke/TestManager.java
  src/main/java/seedu/duke/event/EventManager.java
  src/main/java/seedu/duke/parser/CommandParser.java
  text-ui-test/data/events.txt
Labels: priority.Medium, type.Task

#73 Updated UserGuide.md for Add and Delete test
  docs/UserGuide.md
Labels: priority.High, type.Task

#74 Branch class exception
  src/main/java/seedu/duke/ClassManager.java
  src/main/java/seedu/duke/exception/InvalidClassInputException.java
  src/main/java/seedu/duke/parser/CommandParser.java
Labels: priority.Medium, type.Task

#76 Date time parser
  src/main/java/seedu/duke/TestManager.java
  src/main/java/seedu/duke/parser/DateTimeParser.java
  src/test/java/seedu/duke/AddTestJUnitTest.java
  src/test/java/seedu/duke/DeleteTestJUnitTest.java
Labels: priority.Medium, type.Task

#78 Branch class logging
  src/main/java/seedu/duke/ClassManager.java
Labels: priority.Medium, type.Task

#81 Date time parser
  data/events.txt
  src/main/java/seedu/duke/CcaManager.java
  src/main/java/seedu/duke/ClassManager.java
  src/main/java/seedu/duke/TestManager.java
  src/main/java/seedu/duke/parser/DateTimeParser.java
Labels: priority.Medium, type.Task

#83 Updated UserGuide.md to for date and time format
  docs/UserGuide.md
Labels: priority.Medium, type.Task

#79 Implement assertions for add and delete class features
  data/events.txt
  src/main/java/seedu/duke/ClassManager.java
Labels: priority.Medium, type.Task

#86 add JUnit test for ccaManager
  src/main/java/seedu/duke/CcaManager.java
  src/main/java/seedu/duke/TestManager.java
  src/main/java/seedu/duke/parser/CommandParser.java
  src/test/java/seedu/duke/AddCcaJUnitTest.java
  src/test/java/seedu/duke/DeleteCcaJUnitTest.java
Labels: priority.Medium, type.Task

#92 Removed data file from git track
  data/events.txt
Labels: priority.High, severity.High, type.Bug

#98 Branch add delete class ug
  docs/UserGuide.md
  src/main/java/seedu/duke/ClassManager.java
  src/test/java/seedu/duke/DeleteClassJUnitTest.java
  text-ui-test/data/events.txt
Labels: priority.Medium, type.Task

#99 Update UserGuide for help command
  docs/UserGuide.md
Labels: priority.Medium, type.Task

#104 Implement done feature for class
  src/main/java/seedu/duke/ClassManager.java
  src/main/java/seedu/duke/parser/CommandParser.java
  src/main/java/seedu/duke/parser/CommandType.java
Labels: priority.Medium, type.Task

#106 fix bug of input list
  src/main/java/seedu/duke/parser/CommandParser.java
Labels: type.Bug

#107 Branch update ug
  docs/UserGuide.md
  src/main/java/seedu/duke/parser/CommandParser.java
Labels: priority.Medium, type.Task

#111 Update UserGuide.md
  docs/UserGuide.md
Labels: priority.Medium, type.Task

#114 Update UserGuide.md command summary due to wrong info for "done" feat…
  docs/UserGuide.md
Labels: priority.Medium

#119 Branch javadoc class and class manager
  src/main/java/seedu/duke/Class.java
  src/main/java/seedu/duke/ClassManager.java
Labels: priority.Medium, type.Task

#120 Branch javadoc help
  src/main/java/seedu/duke/parser/CommandParser.java
Labels: priority.Medium, type.Task

#127 Add list quiz function
  src/main/java/seedu/duke/parser/CommandParser.java
  src/main/java/seedu/duke/quiz/QuizManager.java
Labels: type.Task

#130 Branch tuition
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/duke/ListSchedule.java
  src/main/java/seedu/duke/Tuition.java
  src/main/java/seedu/duke/TuitionManager.java
  src/main/java/seedu/duke/event/EventManager.java
  src/main/java/seedu/duke/event/EventParameter.java
  src/main/java/seedu/duke/exception/EmptyTuitionInputException.java
  src/main/java/seedu/duke/exception/InvalidTuitionInputException.java
  src/main/java/seedu/duke/parser/CommandParser.java
  src/main/java/seedu/duke/parser/CommandType.java
  src/main/java/seedu/duke/storage/EventListDecoder.java
  src/main/java/seedu/duke/storage/EventListEncoder.java
  src/main/java/seedu/duke/storage/EventStorageManager.java
  src/test/java/seedu/duke/ListScheduleTest.java
  src/test/java/seedu/duke/StorageTest.java
  test/ValidData.txt
Labels: priority.Medium, type.Story

#131 Add Contact features
  src/main/java/seedu/duke/CcaManager.java
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/duke/contact/Contact.java
  src/main/java/seedu/duke/contact/ContactManager.java
  src/main/java/seedu/duke/exception/ContactEmptyStringException.java
  src/main/java/seedu/duke/exception/ContactParamException.java
  src/main/java/seedu/duke/parser/CommandParser.java
  src/main/java/seedu/duke/parser/CommandType.java
Labels: type.Task

#138 Update help feature with new features for v2.0
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/duke/parser/CommandParser.java
  src/main/java/seedu/duke/quiz/QuizManager.java
  text-ui-test/EXPECTED.TXT
Labels: priority.High, type.Task

#140 Branch user interface
  src/main/java/seedu/duke/CcaManager.java
  src/main/java/seedu/duke/ClassManager.java
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/duke/LogManager.java
  src/main/java/seedu/duke/TestManager.java
  src/main/java/seedu/duke/TuitionManager.java
  src/main/java/seedu/duke/common/Messages.java
  src/main/java/seedu/duke/contact/ContactManager.java
  src/main/java/seedu/duke/event/EventManager.java
  src/main/java/seedu/duke/parser/CommandParser.java
  src/main/java/seedu/duke/parser/CommandType.java
  src/main/java/seedu/duke/storage/EventStorageManager.java
  src/main/java/seedu/duke/storage/QuizStorageManager.java
  src/main/java/seedu/duke/ui/UserInterface.java
Labels: priority.Low, type.Task

#153 List date
  .gitignore
  README.md
  docs/UserGuide.md
  src/main/java/seedu/duke/Event.java
  src/main/java/seedu/duke/ListSchedule.java
  src/main/java/seedu/duke/controller/parser/DateTimeParser.java
  src/main/java/seedu/duke/model/event/EventManager.java
  src/main/java/seedu/duke/model/event/cca/Cca.java
  src/main/java/seedu/duke/model/event/cca/EventCca.java
  src/main/java/seedu/duke/model/event/cca/EventCcaManager.java
  src/main/java/seedu/duke/model/event/classlesson/Class.java
  src/main/java/seedu/duke/model/event/classlesson/EventClass.java
  src/main/java/seedu/duke/model/event/classlesson/EventClassManager.java
  src/main/java/seedu/duke/model/event/test/EventTest.java
  src/main/java/seedu/duke/model/event/test/EventTestManager.java
  src/main/java/seedu/duke/model/event/test/Test.java
  src/main/java/seedu/duke/model/event/tuition/EventTuition.java
  src/main/java/seedu/duke/model/event/tuition/EventTuitionManager.java
  src/main/java/seedu/duke/model/event/tuition/Tuition.java
  src/main/java/seedu/duke/parser/CommandParser.java
  src/main/java/seedu/duke/parser/CommandType.java
  src/main/java/seedu/duke/storage/EventListDecoder.java
  src/main/java/seedu/duke/storage/EventListEncoder.java
  src/main/java/seedu/duke/storage/EventStorageManager.java
  src/test/java/seedu/duke/AddEventCcaJUnitTest.java
  src/test/java/seedu/duke/AddEventClassJUnitTest.java
  src/test/java/seedu/duke/AddTestJUnitTest.java
  src/test/java/seedu/duke/DeleteEventCcaJUnitTest.java
  src/test/java/seedu/duke/DeleteEventClassJUnitTest.java
  src/test/java/seedu/duke/DeleteTestJUnitTest.java
  src/test/java/seedu/duke/DoneEventCcaJUnitTest.java
  src/test/java/seedu/duke/DoneTestJUnitTest.java
  src/test/java/seedu/duke/ListScheduleTest.java
  src/test/java/seedu/duke/StorageTest.java
  test/ValidData.txt
Labels: priority.High, type.Task

#162 Branch fix bug incomplete list command
  src/main/java/seedu/duke/common/Messages.java
  src/main/java/seedu/duke/controller/ControlManager.java
  src/main/java/seedu/duke/exception/IncompleteListCommandException.java
Labels: priority.High, type.Bug

#166 Update mistake in IncompleteListCommandException to extend Exception …
  src/main/java/seedu/duke/exception/IncompleteListCommandException.java
Labels: priority.High, type.Bug

#167 Branch plant uml add
  docs/Add.puml
Labels: priority.Medium

#171 Branch storage corrupted exception
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/duke/common/Messages.java
  src/main/java/seedu/duke/controller/ControlManager.java
  src/main/java/seedu/duke/exception/StorageCorruptedException.java
  src/main/java/seedu/duke/exception/StorageSeparatorException.java
  src/main/java/seedu/duke/storage/EventListDecoder.java
  src/main/java/seedu/duke/storage/EventStorageManager.java
  src/main/java/seedu/duke/ui/UserInterface.java
Labels: priority.High, severity.High, type.Bug

#172 Branch planUML help
  docs/diagram/Add.puml
  docs/diagram/Help.puml
Labels: priority.Medium, type.Task

#175 List week
  docs/diagram/DeleteFeatureDiagram.puml
  docs/diagram/DoneFeatureDiagram.puml
  src/main/java/seedu/duke/controller/parser/DateTimeParser.java
  src/main/java/seedu/duke/model/event/EventManager.java
  src/main/java/seedu/duke/model/event/ListSchedule.java
Labels: priority.High, type.Task

#173 Branch plantUML Add
  docs/diagram/Add.puml
Labels: priority.Medium, type.Task

#184 Update Logo from Duke to Plan&Score
  src/main/java/seedu/duke/common/Messages.java
  text-ui-test/EXPECTED.TXT
Labels: priority.Low, type.Task

#189 Branch render week schedule list
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/duke/common/Messages.java
  src/main/java/seedu/duke/model/event/Event.java
  src/main/java/seedu/duke/model/event/EventManager.java
  src/main/java/seedu/duke/model/event/cca/EventCca.java
  src/main/java/seedu/duke/model/event/classlesson/EventClass.java
  src/main/java/seedu/duke/model/event/test/EventTest.java
  src/main/java/seedu/duke/model/event/tuition/EventTuition.java
  src/main/java/seedu/duke/ui/CalendarWeekRenderer.java
  src/main/java/seedu/duke/ui/CalendarWeekRendererUtils.java
  src/test/java/seedu/duke/model/event/ListScheduleTest.java
Labels: priority.Medium, type.Enhancement

#187 Branch quiz update
  src/main/java/seedu/duke/common/Messages.java
  src/main/java/seedu/duke/controller/ControlManager.java
  src/main/java/seedu/duke/controller/command/CommandFactory.java
  src/main/java/seedu/duke/controller/command/QuizCommand.java
  src/main/java/seedu/duke/controller/parser/CommandParser.java
  src/main/java/seedu/duke/controller/parser/CommandType.java
  src/main/java/seedu/duke/controller/parser/ModelParser.java
  src/main/java/seedu/duke/model/event/classlesson/EventClass.java
  src/main/java/seedu/duke/model/event/classlesson/EventClassManager.java
  src/main/java/seedu/duke/model/quiz/Quiz.java
  src/main/java/seedu/duke/model/quiz/QuizManager.java
  src/main/java/seedu/duke/model/quiz/UserAnswerManager.java
  text-ui-test/EXPECTED.TXT
Labels: priority.High, type.Task

#192 User guide list event week
  docs/UserGuide.md
  src/main/java/seedu/duke/model/event/ListSchedule.java
  src/test/java/seedu/duke/model/event/ListScheduleTest.java
Labels: priority.Medium, type.Task

#195 Branch user guide
  docs/UserGuide.md
  src/test/java/seedu/duke/model/event/ListScheduleTest.java
Labels: priority.High, severity.High, type.Bug, type.Task

#186 Update help feature
  src/main/java/seedu/duke/common/Messages.java
Labels: priority.Low, type.Task

#200 Update authorship
  src/main/java/seedu/duke/common/Messages.java
  src/main/java/seedu/duke/controller/parser/DateTimeParser.java
  src/main/java/seedu/duke/model/event/Event.java
  src/main/java/seedu/duke/model/event/EventManager.java
  src/main/java/seedu/duke/model/event/ListSchedule.java
  src/main/java/seedu/duke/model/event/cca/EventCca.java
  src/main/java/seedu/duke/model/event/test/EventTest.java
  src/main/java/seedu/duke/model/event/tuition/EventTuition.java
  src/main/java/seedu/duke/model/event/tuition/EventTuitionManager.java
  src/main/java/seedu/duke/storage/EventListDecoder.java
  src/main/java/seedu/duke/storage/EventListEncoder.java
  src/main/java/seedu/duke/storage/EventStorageManager.java
  src/main/java/seedu/duke/storage/StorageManager.java
  src/main/java/seedu/duke/ui/CalendarWeekRenderer.java
  src/main/java/seedu/duke/ui/CalendarWeekRendererUtils.java
  src/main/java/seedu/duke/ui/UserInterface.java
  src/test/java/seedu/duke/StorageTest.java
Labels: type.Task

#202 Add tests for Tuition class
  src/test/java/seedu/duke/AddEventTuitionJUnitTest.java
  src/test/java/seedu/duke/DoneEventTuitionJUnitTest.java
Labels: priority.High, type.Task

#207 Converted to Calendar format
  docs/UserGuide.md
  src/main/java/seedu/duke/controller/parser/DateTimeParser.java
  src/main/java/seedu/duke/model/event/Event.java
  src/main/java/seedu/duke/model/event/EventManager.java
  src/main/java/seedu/duke/model/event/ListSchedule.java
  src/main/java/seedu/duke/model/event/cca/EventCca.java
  src/main/java/seedu/duke/model/event/cca/EventCcaManager.java
  src/main/java/seedu/duke/model/event/classlesson/EventClass.java
  src/main/java/seedu/duke/model/event/classlesson/EventClassManager.java
  src/main/java/seedu/duke/model/event/test/EventTest.java
  src/main/java/seedu/duke/model/event/test/EventTestManager.java
  src/main/java/seedu/duke/model/event/tuition/EventTuition.java
  src/main/java/seedu/duke/model/event/tuition/EventTuitionManager.java
  src/main/java/seedu/duke/storage/EventListDecoder.java
  src/main/java/seedu/duke/storage/EventListEncoder.java
  src/main/java/seedu/duke/ui/CalendarWeekRenderer.java
  src/test/java/seedu/duke/AddEventCcaJUnitTest.java
  src/test/java/seedu/duke/AddEventClassJUnitTest.java
  src/test/java/seedu/duke/AddEventTuitionJUnitTest.java
  src/test/java/seedu/duke/AddTestJUnitTest.java
  src/test/java/seedu/duke/DeleteEventCcaJUnitTest.java
  src/test/java/seedu/duke/DeleteEventClassJUnitTest.java
  src/test/java/seedu/duke/DeleteTestJUnitTest.java
  src/test/java/seedu/duke/DoneEventCcaJUnitTest.java
  src/test/java/seedu/duke/DoneEventTuitionJUnitTest.java
  src/test/java/seedu/duke/DoneTestJUnitTest.java
  src/test/java/seedu/duke/StorageTest.java
  src/test/java/seedu/duke/model/event/ListScheduleTest.java
Labels: priority.Medium, type.Task

#209 Branch refactor calendar
  src/main/java/seedu/duke/controller/parser/DateTimeParser.java
  src/main/java/seedu/duke/model/event/EventManager.java
  src/main/java/seedu/duke/model/event/EventParameter.java
  src/main/java/seedu/duke/model/event/ListSchedule.java
  src/main/java/seedu/duke/model/event/cca/EventCca.java
  src/main/java/seedu/duke/model/event/cca/EventCcaManager.java
  src/main/java/seedu/duke/model/event/classlesson/EventClass.java
  src/main/java/seedu/duke/model/event/classlesson/EventClassManager.java
  src/main/java/seedu/duke/model/event/test/EventTest.java
  src/main/java/seedu/duke/model/event/test/EventTestManager.java
  src/main/java/seedu/duke/model/event/tuition/EventTuition.java
  src/main/java/seedu/duke/model/event/tuition/EventTuitionManager.java
  src/main/java/seedu/duke/storage/EventListDecoder.java
  src/main/java/seedu/duke/storage/EventListEncoder.java
  src/main/java/seedu/duke/ui/CalendarWeekRenderer.java
  src/test/java/seedu/duke/AddEventCcaJUnitTest.java
  src/test/java/seedu/duke/AddEventClassJUnitTest.java
  src/test/java/seedu/duke/AddEventTuitionJUnitTest.java
  src/test/java/seedu/duke/AddTestJUnitTest.java
  src/test/java/seedu/duke/DeleteEventCcaJUnitTest.java
  src/test/java/seedu/duke/DeleteEventClassJUnitTest.java
  src/test/java/seedu/duke/DeleteTestJUnitTest.java
  src/test/java/seedu/duke/DoneEventCcaJUnitTest.java
  src/test/java/seedu/duke/DoneEventTuitionJUnitTest.java
  src/test/java/seedu/duke/DoneTestJUnitTest.java
  src/test/java/seedu/duke/StorageTest.java
  src/test/java/seedu/duke/model/event/ListScheduleTest.java
  test/ValidData.txt
Labels: priority.Medium, type.Task

#210 Branch quiz feature
  src/main/java/seedu/duke/model/quiz/FindQuiz.java
  src/main/java/seedu/duke/model/quiz/Quiz.java
  src/main/java/seedu/duke/model/quiz/QuizManager.java
  src/main/java/seedu/duke/model/quiz/UserAnswerManager.java
Labels: priority.High, type.Task

#212 Fix improper logic called while printing dayOfMonth and Month
  src/main/java/seedu/duke/controller/parser/DateTimeParser.java
  src/main/java/seedu/duke/ui/CalendarWeekRenderer.java
Labels: priority.High, severity.High, type.Bug

#215 Java docs
  src/main/java/seedu/duke/controller/parser/DateTimeParser.java
  src/main/java/seedu/duke/model/event/EventManager.java
  src/main/java/seedu/duke/model/event/ListSchedule.java
  src/main/java/seedu/duke/model/event/test/EventTest.java
  src/main/java/seedu/duke/model/event/test/EventTestManager.java
Labels: priority.Medium, type.Task

#219 Branch quiz assertions
  src/main/java/seedu/duke/model/event/classlesson/EventClassManager.java
  src/main/java/seedu/duke/model/quiz/Quiz.java
  src/main/java/seedu/duke/model/quiz/QuizManager.java
  src/main/java/seedu/duke/model/quiz/UserAnswerManager.java
Labels: priority.Medium, type.Task

#222 Branch check event clash
  src/main/java/seedu/duke/exception/InvalidDateException.java
  src/main/java/seedu/duke/exception/InvalidDateType.java
  src/main/java/seedu/duke/model/event/EventManager.java
  src/main/java/seedu/duke/model/event/cca/EventCcaManager.java
  src/main/java/seedu/duke/model/event/classlesson/EventClassManager.java
  src/main/java/seedu/duke/model/event/test/EventTestManager.java
  src/main/java/seedu/duke/model/event/tuition/EventTuitionManager.java
  src/test/java/seedu/duke/AddEventCcaJUnitTest.java
  src/test/java/seedu/duke/AddEventClassJUnitTest.java
  src/test/java/seedu/duke/AddEventTuitionJUnitTest.java
  src/test/java/seedu/duke/AddTestJUnitTest.java
  src/test/java/seedu/duke/DeleteEventCcaJUnitTest.java
  src/test/java/seedu/duke/DeleteEventClassJUnitTest.java
  src/test/java/seedu/duke/DeleteTestJUnitTest.java
  src/test/java/seedu/duke/DoneEventCcaJUnitTest.java
  src/test/java/seedu/duke/DoneEventTuitionJUnitTest.java
  src/test/java/seedu/duke/DoneTestJUnitTest.java
  src/test/java/seedu/duke/StorageTest.java
  src/test/java/seedu/duke/TestUtils.java
Labels: priority.High, type.Task

#227 Fix bug where an invalid event can still be added to list
  src/main/java/seedu/duke/controller/parser/DateTimeParser.java
  src/main/java/seedu/duke/model/event/cca/EventCcaManager.java
  src/main/java/seedu/duke/model/event/classlesson/EventClassManager.java
  src/main/java/seedu/duke/model/event/test/EventTestManager.java
  src/main/java/seedu/duke/model/event/tuition/EventTuitionManager.java
  src/main/java/seedu/duke/storage/EventListDecoder.java
  src/test/java/seedu/duke/AddEventTuitionJUnitTest.java
  src/test/java/seedu/duke/DoneEventTuitionJUnitTest.java
  src/test/java/seedu/duke/StorageTest.java
  src/test/java/seedu/duke/TestUtils.java
  src/test/java/seedu/duke/model/event/ListScheduleTest.java
  test/ValidData.txt
Labels: priority.High, type.Bug

#229 Fix list date
  build.gradle
  src/main/java/seedu/duke/controller/parser/DateTimeParser.java
  src/main/java/seedu/duke/model/event/Event.java
  src/main/java/seedu/duke/model/event/EventManager.java
  src/main/java/seedu/duke/model/event/ListSchedule.java
  src/main/java/seedu/duke/model/event/cca/EventCcaManager.java
  src/main/java/seedu/duke/model/event/classlesson/EventClassManager.java
  src/main/java/seedu/duke/model/event/test/EventTestManager.java
  src/main/java/seedu/duke/model/event/tuition/EventTuitionManager.java
Labels: priority.Medium, type.Task

#236 Fix bug due to improper logic disallowing adding of events that fall …
  src/main/java/seedu/duke/model/event/EventManager.java
Labels: priority.High, severity.High, type.Bug

#238 Branch storage
  src/main/java/seedu/duke/model/ConfigParameter.java
  src/main/java/seedu/duke/storage/ConfigDecoder.java
  src/main/java/seedu/duke/storage/ConfigEncoder.java
  src/main/java/seedu/duke/storage/ConfigStorageManager.java
  text-ui-test/EXPECTED.TXT
  text-ui-test/input.txt
Labels: priority.High, type.Task

#242 Branch quiz update
  src/main/java/seedu/duke/common/Messages.java
  src/main/java/seedu/duke/model/quiz/QuizManager.java
  tp/unused/QuizManager_takeQuiz.txt
Labels: priority.High, type.Task

#244 Branch quiz update 2
  src/main/java/seedu/duke/common/Messages.java
  src/main/java/seedu/duke/controller/command/QuizCommand.java
  src/main/java/seedu/duke/model/quiz/QuizManager.java
Labels: priority.High, type.Task

#245 Branch refactor user interface
  src/main/java/seedu/duke/model/event/EventManager.java
  src/main/java/seedu/duke/ui/UserInterface.java
Labels: priority.Medium, type.Task

#248 Recommended hours
  src/main/java/seedu/duke/controller/parser/DateTimeParser.java
  src/main/java/seedu/duke/model/event/EventManager.java
  src/main/java/seedu/duke/model/event/cca/EventCcaManager.java
  src/main/java/seedu/duke/model/event/classlesson/EventClassManager.java
  src/main/java/seedu/duke/model/event/test/EventTestManager.java
  src/main/java/seedu/duke/model/event/tuition/EventTuitionManager.java
  src/test/java/seedu/duke/AddTestJUnitTest.java
  src/test/java/seedu/duke/controller/EventManagerTest.java
Labels: priority.High, type.Task

#251 Update help feature (remove done and update quiz)
  src/main/java/seedu/duke/common/Messages.java
Labels: priority.Low, type.Task

#253 Upload help and add png
  docs/diagram/Add.png
  docs/diagram/Help.png
Labels: priority.Medium, type.Task

#259 Upload delete feature png
  docs/diagram/DeleteFeatureDiagram.png
Labels: priority.Medium, type.Task

#257 Store name and hours
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/duke/common/Messages.java
  src/main/java/seedu/duke/controller/ControlManager.java
  src/main/java/seedu/duke/model/ConfigParameter.java
  src/main/java/seedu/duke/model/event/EventManager.java
  src/main/java/seedu/duke/model/event/tuition/EventTuitionManager.java
  src/main/java/seedu/duke/storage/ConfigDecoder.java
  src/main/java/seedu/duke/storage/ConfigEncoder.java
  src/main/java/seedu/duke/storage/ConfigStorageManager.java
  src/main/java/seedu/duke/ui/UserInterface.java
  src/test/java/seedu/duke/TestUtils.java
  src/test/java/seedu/duke/controller/EventManagerTest.java
  src/test/java/seedu/duke/controller/ModelExtractorTest.java
  text-ui-test/EXPECTED.TXT
  text-ui-test/input.txt
Labels: priority.High, type.Task

#260 Add and upload StorageManager class puml and png
  docs/diagram/StorageManager.png
  docs/diagram/StorageManager.puml
Labels: priority.Medium, type.Task

#261 Branch developer guide
  docs/design/UserInterfaceComponent.puml
  docs/diagram/EventStorageManager.png
  docs/diagram/EventStorageManager.puml
  docs/diagram/ExampleSequence.png
  docs/diagram/ExampleSequence.puml
  docs/diagram/ListWeekSequence.puml
  docs/diagram/StorageComponent.png
  docs/diagram/StorageComponent.puml
  docs/diagram/StorageSequence.png
  docs/diagram/StorageSequence.puml
  docs/diagram/UserInterfaceComponent.puml
  src/main/java/seedu/duke/ui/UserInterface.java
Labels: priority.High, type.Task

#263 Plant uml
  docs/diagram/ConfigStorage.png
  docs/diagram/ConfigStorage.puml
  docs/diagram/StorageManager.png
Labels: priority.Low, type.Task

#266 Update User Guide
  docs/UserGuide.md
Labels: priority.Medium, type.Task

#265 Branch developer guide
  docs/DeveloperGuide.md
  docs/diagram/EventStorageReadSequence.png
  docs/diagram/EventStorageReadSequence.puml
  docs/diagram/EventStorageSaveSequence.png
  docs/diagram/EventStorageSaveSequence.puml
  docs/diagram/UserInterfaceComponent.png
Labels: priority.High

#269 Branch user guide
  docs/UserGuide.md
  docs/images/add_class_invalid_date_given.PNG
  docs/images/initialization.png
Labels: priority.High, type.Task

#270 Update UserGuide.md
  docs/UserGuide.md
Labels: priority.High, type.Task

#272 Update Guides
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: priority.High, type.Task

#281 Update CalendarWeekRenderer to produce next week's schedule
  src/main/java/seedu/duke/controller/parser/DateTimeParser.java
  src/main/java/seedu/duke/model/event/EventManager.java
  src/main/java/seedu/duke/model/event/ListWeekCommand.java
  src/main/java/seedu/duke/model/event/cca/EventCcaManager.java
  src/main/java/seedu/duke/model/event/classlesson/EventClassManager.java
  src/main/java/seedu/duke/model/event/test/EventTestManager.java
  src/main/java/seedu/duke/model/event/tuition/EventTuitionManager.java
  src/main/java/seedu/duke/ui/CalendarWeekRenderer.java
  src/main/java/seedu/duke/ui/CalendarWeekRendererUtils.java
  src/main/java/seedu/duke/ui/UserInterface.java
Labels: priority.Medium, type.Enhancement, type.Task
