Repository AY2021S1-CS2113T-W12-4/tp, pull requests merged in 2020-11, with the labels that each got.

#326 Fixed Bug for recommended hours
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/duke/common/Messages.java
Labels: priority.High, severity.High, type.Bug

#327 Did edit hours
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/duke/common/Messages.java
  src/main/java/seedu/duke/controller/ControlManager.java
  src/main/java/seedu/duke/controller/command/CommandFactory.java
  src/main/java/seedu/duke/controller/command/SetHoursCommand.java
  src/main/java/seedu/duke/controller/parser/CommandParser.java
  src/main/java/seedu/duke/controller/parser/CommandType.java
  src/main/java/seedu/duke/controller/parser/ModelExtractor.java
  src/main/java/seedu/duke/controller/parser/ModelParser.java
  src/main/java/seedu/duke/controller/parser/ModelType.java
  src/main/java/seedu/duke/model/Model.java
  src/main/java/seedu/duke/ui/ConfigManager.java
  src/test/java/seedu/duke/controller/ControlManagerTest.java
  src/test/java/seedu/duke/controller/ModelExtractorTest.java
Labels: priority.High, severity.Medium, type.Enhancement

#331 Fix CalendarWeekRenderer bug of printing break time in wrong column
  src/main/java/seedu/duke/ui/CalendarWeekRenderer.java
Labels: priority.High, severity.High, type.Bug

#334 Java docs time left when adding&deleting events
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/duke/controller/command/SetHoursCommand.java
  src/main/java/seedu/duke/model/event/EventManager.java
  src/main/java/seedu/duke/model/event/cca/EventCcaManager.java
  src/main/java/seedu/duke/model/event/classlesson/EventClassManager.java
  src/main/java/seedu/duke/model/event/test/EventTestManager.java
  src/main/java/seedu/duke/model/event/tuition/EventTuitionManager.java
  src/main/java/seedu/duke/ui/ConfigManager.java
  src/test/java/seedu/duke/controller/EventManagerTest.java
Labels: priority.Low, type.Task

#335 Branch user guide
  docs/UserGuide.md
Labels: priority.Low, severity.Low, type.Bug

#337 did time left for list event today and list event date
  src/main/java/seedu/duke/model/event/EventManager.java
  src/main/java/seedu/duke/model/event/ListSchedule.java
  src/test/java/seedu/duke/model/event/ListScheduleTest.java
Labels: priority.Low, type.Enhancement

#338 Update QuizManager to reject non-number answers and numbers that are …
  src/main/java/seedu/duke/common/Messages.java
  src/main/java/seedu/duke/exception/InvalidInputException.java
  src/main/java/seedu/duke/model/quiz/Quiz.java
  src/main/java/seedu/duke/model/quiz/QuizManager.java
  src/main/java/seedu/duke/storage/QuizListDecoder.java
  src/test/java/seedu/duke/model/quiz/AddQuizJUnitTest.java
Labels: priority.Medium, severity.Medium, type.Bug

#342 Update first draft of PPP
  docs/team/johndoe.md
Labels: type.Task

#345 Branch developer guide
  docs/plantuml/EventStorageReadSequence.puml
  docs/plantuml/EventStorageSaveSequence.puml
  docs/plantuml/ListWeekSequence.puml
  docs/plantuml/UserInterfaceComponent.puml
Labels: priority.Medium, type.Bug

#352 Branch refactor calendar
  src/main/java/seedu/duke/ui/CalendarWeekRenderer.java
  src/main/java/seedu/duke/ui/CalendarWeekRendererUtils.java
Labels: priority.Medium, type.Task

#353 Rename certain constants to avoid magic numbers
  src/main/java/seedu/duke/ui/CalendarWeekRendererUtils.java
Labels: type.Enhancement

#355 Branch user interface
  logfile.txt.1
  src/main/java/seedu/duke/common/Messages.java
  src/main/java/seedu/duke/model/contact/ContactManager.java
  src/main/java/seedu/duke/model/event/EventManager.java
  src/main/java/seedu/duke/model/event/cca/EventCcaManager.java
  src/main/java/seedu/duke/model/event/classlesson/EventClassManager.java
  src/main/java/seedu/duke/model/event/test/EventTestManager.java
  src/main/java/seedu/duke/model/event/tuition/EventTuitionManager.java
  src/main/java/seedu/duke/model/quiz/QuizManager.java
  src/main/java/seedu/duke/ui/ConfigManager.java
  src/main/java/seedu/duke/ui/UserInterface.java
Labels: priority.Medium, type.Enhancement

#359 Do welcome screen
  logfile.txt.1
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/duke/ui/ConfigManager.java
  src/main/java/seedu/duke/ui/UserInterface.java
  text-ui-test/EXPECTED.TXT
Labels: priority.Low, severity.Low, type.Enhancement, type.Task

#366 Updated Userguide & Inserted diagrams
  docs/AboutUs.md
  docs/UserGuide.md
  docs/images/add_cca_1.png
  docs/images/add_cca_2.png
  docs/images/add_class_2.png
  docs/images/add_test_1.png
  docs/images/add_test_2.png
  docs/images/add_tuition_1.png
  docs/images/add_tuition_2.png
  docs/images/bye_1.png
  docs/images/bye_2.png
  docs/images/class_error.png
  docs/images/delete_cca_1.png
  docs/images/delete_cca_2.png
  docs/images/delete_class.png
  docs/images/delete_test_1.png
  docs/images/delete_test_2.png
  docs/images/delete_tuition_1.png
  docs/images/delete_tuition_2.png
  docs/images/help_command_1.png
  docs/images/help_command_2.png
  docs/images/list_event_1.png
  docs/images/list_event_2.png
  docs/images/list_event_date_1.png
  docs/images/list_event_date_2.png
  docs/images/list_event_nextweek_1.png
  docs/images/list_event_nextweek_2.png
  docs/images/list_event_today_1.png
  docs/images/list_event_today_2.png
  docs/images/list_event_week_1.png
  docs/images/list_event_week_2.png
  logfile.txt.1
  src/main/java/seedu/duke/common/Messages.java
  src/main/java/seedu/duke/model/event/test/EventTest.java
  src/main/java/seedu/duke/model/event/test/EventTestManager.java
  src/main/java/seedu/duke/ui/ConfigManager.java
Labels: severity.Low, type.Enhancement, type.Task

#370 Update User Guide (Handle indentation of command 14)
  docs/UserGuide.md
Labels: priority.High, type.Bug

#372 Update QuizManager.java (Assertions)
  src/main/java/seedu/duke/model/event/classlesson/EventClassManager.java
  src/main/java/seedu/duke/model/quiz/QuizManager.java
Labels: priority.High, type.Bug

#374 Edit DG Quiz Feature (improve readability)
  docs/DeveloperGuide.md
Labels: priority.Medium, type.Task

#375 Branch storage corrupted exception
  src/main/java/seedu/duke/Main.java
  src/main/java/seedu/duke/common/Messages.java
  src/main/java/seedu/duke/storage/StorageManager.java
  src/main/java/seedu/duke/storage/event/EventStorageManager.java
  src/test/java/seedu/duke/StorageTest.java
  src/test/java/seedu/duke/TestUtils.java
  testdata/invaliddata.txt
  testdata/validdata.txt
Labels: priority.High, type.Enhancement

#377 Relocate unused file (QuizManager)
  src/main/java/seedu/duke/unused/QuizManager
  tp/unused/QuizManager_takeQuiz.txt
Labels: priority.Medium, type.Task

#367 Added more images and updated the userguide
  docs/UserGuide.md
  docs/images/add_cca_error.png
  docs/images/add_class_invalid_date_given.PNG
  docs/images/add_test_error.png
  docs/images/add_tuition_error.png
  docs/images/addclass2.png
  docs/images/delete_cca_error.png
  docs/images/delete_class.png
  docs/images/delete_class_1.png
  docs/images/delete_class_2.png
  docs/images/delete_class_error.png
  docs/images/delete_test_error.png
  docs/images/delete_tuition_error.png
  docs/images/finish_intro.png
  docs/images/help1.png
  docs/images/help2.png
  docs/images/hours.png
  docs/images/intro_screen.png
  docs/images/name.png
  docs/images/set_hours_1.png
  docs/images/set_hours_2.png
  docs/images/set_hours_3.png
  docs/images/set_hours_error.png
Labels: priority.Medium, type.Enhancement, type.Task

#379 Updated UserGuide, redid Message for Prompting hours & refactored packages
  docs/UserGuide.md
  docs/images/set_hours_2.png
  logfile.txt.1
  src/main/java/seedu/duke/common/Messages.java
  src/test/java/seedu/duke/controller/EventManagerTest.java
  src/test/java/seedu/duke/model/event/cca/AddEventCcaJUnitTest.java
  src/test/java/seedu/duke/model/event/cca/DeleteEventCcaJUnitTest.java
  src/test/java/seedu/duke/model/event/cca/DoneEventCcaJUnitTest.java
  src/test/java/seedu/duke/model/event/classlesson/AddEventClassJUnitTest.java
  src/test/java/seedu/duke/model/event/classlesson/DeleteEventClassJUnitTest.java
  src/test/java/seedu/duke/model/event/test/AddTestJUnitTest.java
  src/test/java/seedu/duke/model/event/test/DeleteTestJUnitTest.java
  src/test/java/seedu/duke/model/event/test/DoneTestJUnitTest.java
  src/test/java/seedu/duke/model/event/tuition/AddEventTuitionJUnitTest.java
  src/test/java/seedu/duke/model/event/tuition/DoneEventTuitionJUnitTest.java
  src/test/java/seedu/duke/storage/StorageTest.java
  src/test/java/seedu/duke/storage/TestUtils.java
Labels: priority.Medium, type.Enhancement, type.Task

#380 Remove done feature in class feature classes
  src/main/java/seedu/duke/model/event/classlesson/EventClassManager.java
Labels: priority.Medium, type.Bug

#381 Update QuizManager.java
  src/main/java/seedu/duke/model/quiz/QuizManager.java
Labels: priority.Low, type.Task

#382 Redo user guide for hours images
  docs/UserGuide.md
  docs/images/help1.png
  docs/images/hours.png
  docs/images/name.png
  docs/images/set_hours_2.png
  docs/images/set_hours_3.png
  docs/images/set_hours_error.png
  logfile.txt.1
Labels: priority.Medium, type.Enhancement, type.Task

#363 Branch java docs
  src/main/java/seedu/duke/model/event/tuition/EventTuition.java
  src/main/java/seedu/duke/model/event/tuition/EventTuitionManager.java
  src/main/java/seedu/duke/storage/StorageManager.java
  src/main/java/seedu/duke/storage/event/EventListDecoder.java
  src/main/java/seedu/duke/storage/event/EventListEncoder.java
  src/main/java/seedu/duke/storage/event/EventStorageManager.java
  src/main/java/seedu/duke/ui/CalendarWeekRenderer.java
  src/main/java/seedu/duke/ui/CalendarWeekRendererUtils.java
  src/main/java/seedu/duke/ui/ConfigManager.java
  src/main/java/seedu/duke/ui/UserInterface.java
Labels: priority.High, type.Task

#385 Add PPP (elizabethcwt)
  docs/team/elizabethcwt.md
Labels: priority.High, type.Task

#386 Update PPP (elizabethcwt)
  docs/team/elizabethcwt.md
Labels: priority.Low, type.Bug

#389 Branch developer guide
  docs/DeveloperGuide.md
  docs/plantuml/ListWeekSequence.puml
  docs/plantuml/UserInterfaceComponent.puml
  docs/team/durianpancakes.md
Labels: priority.High

#391 Update UG (attach photos to quiz/score component)
  docs/UserGuide.md
  docs/images/deletequiz1.png
  docs/images/findquiz.png
  docs/images/listquiz.png
  docs/images/quiz1.png
  docs/images/quizadded.png
  docs/images/quizrecord.png
Labels: priority.High, type.Task

#394 Update UG and PPP
  docs/UserGuide.md
  docs/team/elizabethcwt.md
Labels: priority.Medium, type.Task

#406 Alicia's PPP
  docs/team/aliciaho.md
Labels: priority.Medium, type.Task

#405 Update corrupt data handling for Quiz and Contact storage
  logfile.txt.1
  src/main/java/seedu/duke/Main.java
  src/main/java/seedu/duke/model/ConfigParameter.java
  src/main/java/seedu/duke/storage/config/ConfigDecoder.java
  src/main/java/seedu/duke/storage/config/ConfigStorageManager.java
  src/main/java/seedu/duke/storage/contact/ContactListDecoder.java
  src/main/java/seedu/duke/storage/contact/ContactStorageManager.java
  src/main/java/seedu/duke/storage/event/EventStorageManager.java
  src/main/java/seedu/duke/storage/quiz/QuizStorageManager.java
  src/main/java/seedu/duke/ui/ConfigManager.java
Labels: priority.High

#407 Update UserGuide's command summary for tuition
  docs/UserGuide.md
Labels: priority.High

#411 Update UG (fix content page bug)
  docs/UserGuide.md
Labels: priority.Low, type.Bug

#413 Branch refactor storage
  src/main/java/seedu/duke/Main.java
  src/main/java/seedu/duke/controller/ControlManager.java
  src/main/java/seedu/duke/controller/parser/DateTimeParser.java
  src/main/java/seedu/duke/model/event/EventManager.java
  src/main/java/seedu/duke/storage/StorageExceptionHandler.java
  src/main/java/seedu/duke/storage/StorageManager.java
  src/main/java/seedu/duke/storage/event/EventListDecoder.java
  src/main/java/seedu/duke/storage/event/EventListEncoder.java
  src/main/java/seedu/duke/storage/event/EventStorageManager.java
Labels: priority.Medium, type.Task

#415 Updated dg for set hours
  docs/DeveloperGuide.md
  docs/diagram/SetHours.png
  docs/plantuml/SetHours.puml
  docs/team/aliciaho.md
  logfile.txt.1
  src/main/java/seedu/duke/controller/parser/DateTimeParser.java
  src/main/java/seedu/duke/ui/ConfigManager.java
Labels: priority.Medium, type.Enhancement, type.Task

#419 Update about us
  docs/AboutUs.md
Labels: priority.Low, type.Enhancement, type.Task

#420 Update UG (Score component text formatting)
  docs/UserGuide.md
Labels: priority.Medium, type.Task

#424 Add assertions
  src/main/java/seedu/duke/storage/event/EventListDecoder.java
  src/main/java/seedu/duke/ui/CalendarWeekRenderer.java
  testdata/validdata.txt
Labels: priority.High, type.Task

#426 rename getTaskStatement to getTestStatement
  src/main/java/seedu/duke/model/event/test/EventTestManager.java
Labels: priority.Low, type.Enhancement, type.Task

#431 Branch javadoc quiz manager
  src/main/java/seedu/duke/common/Messages.java
  src/main/java/seedu/duke/model/quiz/QuizManager.java
Labels: priority.Medium, type.Task

#430 Branch developer guide
  docs/diagram/EventStorageManager.png
  docs/diagram/EventStorageReadSequence.png
  docs/diagram/EventStorageSaveSequence.png
  docs/diagram/StorageSequence.png
  docs/plantuml/EventStorageManager.puml
  docs/plantuml/EventStorageReadSequence.puml
  docs/plantuml/EventStorageSaveSequence.puml
  docs/plantuml/StorageComponent.puml
  docs/plantuml/StorageSequence.puml
  src/main/java/seedu/duke/storage/StorageExceptionHandler.java
Labels: priority.High, type.Task

#435 Branch javadoc quiz and useranswermanager
  src/main/java/seedu/duke/model/quiz/Quiz.java
  src/main/java/seedu/duke/model/quiz/UserAnswerManager.java
Labels: priority.Medium, type.Task

#441 Update PPP (elizabethcwt)
  docs/team/elizabethcwt.md
Labels: priority.Medium, type.Task

#442 Dgug refinement
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagram/ConfigStorage.png
  docs/plantuml/ConfigStorage.puml
  docs/team/aliciaho.md
Labels: priority.Medium, type.Enhancement, type.Task

#443 Update UG (fix hyperlink)
  docs/UserGuide.md
Labels: priority.Medium, type.Bug

#445 shorten PPP
  docs/team/aliciaho.md
Labels: priority.Low, type.Enhancement

#444 Update Javadocs
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/seedu/duke/exception/InvalidDateException.java
  src/main/java/seedu/duke/exception/InvalidDateType.java
  src/main/java/seedu/duke/exception/StorageSeparatorException.java
  src/main/java/seedu/duke/model/config/ConfigManager.java
  src/main/java/seedu/duke/model/event/ListWeekCommand.java
Labels: priority.Medium, type.Enhancement

#446 Update PPP (elizabethcwt)
  docs/team/elizabethcwt.md
Labels: priority.Medium, type.Bug

#447 Update PPP and DG
  docs/DeveloperGuide.md
  docs/team/durianpancakes.md
Labels: priority.Medium

#448 Refine ppp & Fixed UG hyperlink
  docs/UserGuide.md
  docs/team/aliciaho.md
Labels: priority.Low, type.Enhancement

#452 Branch developer guide
  docs/UserGuide.md
  docs/diagram/UserInterfaceComponent.png
  docs/images/storage_corrupted_factory_reset.PNG
Labels: priority.High, type.Enhancement

#454 Update user stories
  docs/DeveloperGuide.md
Labels: priority.Low, type.Enhancement, type.Task

#457 Update UserGuide.md
  docs/UserGuide.md
Labels: priority.High, type.Enhancement, type.Task
